# -*- coding: utf-8 -*-
"""shopping_scrap_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XfZLGPIg_gZVqKlyt8R8GaCAQmmC1iuc
"""

from bs4 import BeautifulSoup
import re, json
from urllib.parse import urljoin

#otwieramy plik
with open('index.html', 'r', encoding='utf-8') as f:
    html_content = f.read()

soup = BeautifulSoup(html_content, 'html.parser')
print(f"Tytuł strony: {soup.title.get_text(strip=True)}")

BASE = html_content

def text_or_none(node, default=None):
    return node.get_text(" ", strip=True) if node else default

def select_one_text(root, css, default=None):
    el = root.select_one(css)
    return text_or_none(el, default)

def attr_or_none(el, name, default=None):
    return el.get(name, default) if el else default

def parse_price_to_float(txt):
    # obsługa PLN, spacji i przecinków
    if not txt: return None
    m = re.search(r'([0-9]+(?:[.,][0-9]{2})?)', txt)
    if not m: return None
    return float(m.group(1).replace(",", "."))